modLoader="javafml"
loaderVersion="[47,)"
license="MIT License"

[[mods]]
modId="nether_star_generator"
version="1.0.0"
displayName="Nether Star Generator"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="bugpig, MCreator"
description="Simple FE generator"

[[dependencies.nether_star_generator]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="NONE"
    side="BOTH"




